name: clay_monorepo

environment:
  sdk: ">=3.5.0 <4.0.0"

dev_dependencies:
  melos: ^7.5.1
  very_good_analysis: ^10.0.0

melos:
  command:
    bootstrap:
      environment:
        sdk: ">=3.5.0 <4.0.0"

  scripts:
    format.ci:
      description: Format all packages (CI)
      run: dart format --set-exit-if-changed .

    analyze.ci:
      description: Analyze all packages (CI)
      run: dart analyze --fatal-infos --fatal-warnings .

    test.ci:
      description: Run tests for all packages (CI)
      run: >
        melos exec --depends-on test --dir-exists test --fail-fast --
        "dart test --reporter expanded"

workspace:
  - packages/clay_cli/
